version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: "bundle exec pumactl start"
    volumes:
      - ./api:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "8000:3000"
    stdin_open: true
    tty: true
  web:
    build:
      context: ./nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - api
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
