export {default as CompletedPostsDetail} from './CompletedPostsDetail'
export {default as CompletedPostsList} from './CompletedPostsList'
export {default as PostEdit} from './PostEdit'
export {default as ReadingPostsDetail} from './ReadingPostsDetail'
export {default as RegisteredPostsDetail} from './RegisteredPostsDetail'
export {default as RegisteredPostsList} from './RegisteredPostsList'
export {default as SharePostsPage} from './SharePostsPage'
export {default as TopPage} from './TopPage'
