default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  host: <%= ENV["AWS_RDS_HOST"] %>
  database: <%= ENV["AWS_RDS_DATABASE"] %>
  username: <%= ENV["AWS_RDS_USERNAME"] %>
  password: <%= ENV["AWS_RDS_PASSWORD"] %>